import = ["~/.config/sesh/sesh_local.toml"]

[default_session]
startup_command = "pwd"

[[session]]
name = "Home ğŸ¡"
path = "~/"
startup_command = "pwd"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Beancount ğŸ“ˆ"
path = "~/workspace/beancount"
startup_command = "just edit"
