config:
  multi-pane-icon: "ğŸªŸ"
  fallback-icon: "â“" # icon to use if no definition is found
  show-name: false # show the window name with the icon

icons:
  fish: "ğŸ "
  nvim: "ğŸ› ï¸"
  btm: "ğŸ“ˆ"
  cargo: "ğŸ¦€"
  docker: "ğŸ³"
  bun: "ğŸ¥Ÿ"
